packages:
  - 'packages/*'
catalog:
  '@antfu/eslint-config': ^5.2.2
  '@babel/preset-typescript': ^7.24.1
  '@iconify/json': ^2.2.205
  '@modelcontextprotocol/sdk': ^1.15.1
  '@types/babel__core': ^7.20.5
  '@types/babel__traverse': ^7.20.5
  '@types/codemirror': ^5.60.15
  '@types/eslint': ^8.56.10
  '@types/lodash-es': ^4.17.12
  '@types/node': ^20.12.7
  '@types/uuid': ^9.0.8
  '@types/vscode': ^1.78.1
  '@typescript-eslint/utils': ^6.21.0
  '@unocss/nuxt': ^0.54.3
  '@vitest/coverage-istanbul': ^1.5.2
  '@vscode/vsce': ^2.26.0
  '@vueuse/core': ^10.9.0
  '@vueuse/nuxt': ^10.9.0
  bumpp: ^9.4.1
  codemirror: ^5.65.16
  cross-env: ^7.0.3
  eslint: ^9.34.0
  eslint-define-config: ^2.1.0
  eslint-plugin-security: ^3.0.1
  fast-glob: ^3.3.2
  lodash-es: ^4.17.21
  nodemon: ^3.1.0
  nuxt: ^3.11.2
  rimraf: ^5.0.5
  ts-node: ^10.9.2
  tsup: ^8.0.2
  typescript: ^5.4.5
  unbuild: ^2.0.0
  unocss: ^0.54.3
  vis-network: ^9.1.9
  vite: ^4.5.3
  vitest: ^1.5.2
  vscode-ext-gen: ^0.3.1
  zod: ^3.24.2
